void testPopulation( void );
void testIndividual( int );
void testGenes( string , int );
string geneToStringConverter( vector<int> , int , int );
string executeCommand( const char* );
string getEnergy( string );
void selection( void );
void crossover( void );
void mutation( void );
Individual getFittestOffspring( void );
void addFittestOffspring( void );
